version: '3.2'
services:
  frontend:
    build: .
    environment:
       - CHOKIDAR_USEPOLLING=true
    env_file: ./frontend.env
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - /frontend/node_modules
      - .:/frontend
