version: '3.2'
services:
  database:
    image: 'postgres:11'
    restart: always
    ports:
      - '5434:5432'
    env_file: ./database.env
    volumes:
     - 'db_volume:/var/lib/postgresql/data'

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - database
    env_file: auth.env
    ports:
      - '3031:3031'
    command: npm run dev
    volumes:
      - .:/auth/
      -  /auth/node_modules 
volumes:
  db_volume:
    driver: local
